/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author arund
 */
public class Admin_login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_login
     */
    public Admin_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_admin = new javax.swing.JButton();
        admin_username = new javax.swing.JTextField();
        show_password = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enter_username_lbl = new javax.swing.JLabel();
        admin_password = new javax.swing.JPasswordField();
        admin_username1 = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        warning_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 340));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_admin.setBorderPainted(false);
        login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_adminActionPerformed(evt);
            }
        });
        getContentPane().add(login_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 88, 30));

        admin_username.setBorder(null);
        admin_username.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                admin_usernameMouseDragged(evt);
            }
        });
        admin_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_usernameMouseClicked(evt);
            }
        });
        admin_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_usernameActionPerformed(evt);
            }
        });
        admin_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_usernameKeyReleased(evt);
            }
        });
        getContentPane().add(admin_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 145, 116, 20));

        show_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/show (2).png"))); // NOI18N
        show_password.setBorder(null);
        show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(show_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 175, 20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/cover label.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 207, 150, 10));
        getContentPane().add(enter_username_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 130, 20));

        admin_password.setBorder(null);
        admin_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_passwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admin_passwordMouseEntered(evt);
            }
        });
        admin_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_passwordActionPerformed(evt);
            }
        });
        admin_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_passwordKeyReleased(evt);
            }
        });
        getContentPane().add(admin_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 20));

        admin_username1.setBorder(null);
        admin_username1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                admin_username1MouseDragged(evt);
            }
        });
        admin_username1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_username1MouseClicked(evt);
            }
        });
        admin_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_username1ActionPerformed(evt);
            }
        });
        getContentPane().add(admin_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 145, 116, 20));

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-home-page-20.png"))); // NOI18N
        Exit.setText("Home");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        warning_lbl.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        warning_lbl.setForeground(new java.awt.Color(0, 102, 255));
        warning_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(warning_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/login page.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_adminActionPerformed
        
        String username = admin_username.getText();
        String password = admin_password.getText();
        
        if(username.contentEquals("user") && password.contentEquals("password")) {
            setVisible(false);
            Admin_frame frame = new Admin_frame();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
        else {
            if(admin_username.getText().isEmpty() && admin_password.getText().isEmpty()) {
                warning_lbl.setText("Enter username & password");
            }
           
            else if(admin_username.getText().isEmpty()){
                warning_lbl.setText("Enter username");
            }
        
            else if(admin_password.getText().isEmpty()){
                warning_lbl.setText("Enter password");
            }
        
            else {
                warning_lbl.setText("Username or Password entered, is incorrect");
            }
        }
        
    }//GEN-LAST:event_login_adminActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit", "submit", JOptionPane.YES_NO_OPTION);
        
        if(response ==0 ){
            setVisible(false);
            Home frame = new Home();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }

    }//GEN-LAST:event_ExitActionPerformed

    private void admin_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_passwordActionPerformed
        
    }//GEN-LAST:event_admin_passwordActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        login_admin.setOpaque(false);
        login_admin.setContentAreaFilled(false);
        login_admin.setBorderPainted(false);
        
        show_password.setOpaque(false);
        show_password.setContentAreaFilled(false);
        show_password.setBorderPainted(false);
        
        Exit.setOpaque(false);
        Exit.setContentAreaFilled(false);
        Exit.setBorderPainted(false);
    }//GEN-LAST:event_formComponentShown

    private void show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordActionPerformed
        if(admin_password.echoCharIsSet())
            admin_password.setEchoChar((char)0);
        else
            admin_password.setEchoChar('*');
            
        // TODO add your handling code here:
    }//GEN-LAST:event_show_passwordActionPerformed

    private void admin_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_usernameActionPerformed
        
    }//GEN-LAST:event_admin_usernameActionPerformed

    private void admin_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_usernameMouseClicked
        
    }//GEN-LAST:event_admin_usernameMouseClicked

    private void admin_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_passwordMouseClicked
        
    }//GEN-LAST:event_admin_passwordMouseClicked

    private void admin_usernameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_usernameMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_usernameMouseDragged

    private void admin_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_passwordMouseEntered
        
    }//GEN-LAST:event_admin_passwordMouseEntered

    private void admin_username1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_username1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_username1MouseDragged

    private void admin_username1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_username1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_username1MouseClicked

    private void admin_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_username1ActionPerformed

    private void admin_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_usernameKeyReleased
        warning_lbl.setText("");
    }//GEN-LAST:event_admin_usernameKeyReleased

    private void admin_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_passwordKeyReleased
        warning_lbl.setText("");
    }//GEN-LAST:event_admin_passwordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JPasswordField admin_password;
    private javax.swing.JTextField admin_username;
    private javax.swing.JTextField admin_username1;
    private javax.swing.JLabel enter_username_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login_admin;
    private javax.swing.JButton show_password;
    private javax.swing.JLabel warning_lbl;
    // End of variables declaration//GEN-END:variables
}
