/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection_provider.Connection_code;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
/**
 *
 * @author arund
 */
public class Insert_student extends javax.swing.JFrame {

    /**
     * Creates new form Insert_student
     */
    public Insert_student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        rollno_txt = new javax.swing.JTextField();
        father_txt = new javax.swing.JTextField();
        gender_cbx = new javax.swing.JComboBox<>();
        course_cbx = new javax.swing.JComboBox<>();
        branch_cbx = new javax.swing.JComboBox<>();
        submit_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 450));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 37, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Roll No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 63, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 63, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Father's name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Course name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 73, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Branch");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, -1));
        getContentPane().add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 71, -1));
        getContentPane().add(rollno_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 71, -1));
        getContentPane().add(father_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 71, -1));

        gender_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        gender_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_cbxActionPerformed(evt);
            }
        });
        getContentPane().add(gender_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        course_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "BTech" }));
        getContentPane().add(course_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        branch_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CS", "ECE", "Mech", "EEE", "Civil" }));
        getContentPane().add(branch_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        submit_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 80, -1));

        clear_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear_btn.setText("Clear");
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter all the details of the student");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-back-arrow-30.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        exit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-close-30.png"))); // NOI18N
        exit1.setText("Exit");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 90, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic2.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -220, 1180, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        String name = name_txt.getText();
        String rollno = rollno_txt.getText();
        String gender = (String)gender_cbx.getSelectedItem();
        String fathername = father_txt.getText();
        String course = (String)course_cbx.getSelectedItem();
        String branch = (String)branch_cbx.getSelectedItem();

        try{
            Connection con = Connection_code.get_con();
            Statement st = con.createStatement();
            st.executeUpdate("insert into student values('"+ name + "', '" + rollno +"', '"+ gender +"', '"+ fathername +"', '"+ course +"', '"+ branch +"')");
            JOptionPane.showMessageDialog(null, "Insertion Successful");
            setVisible(false);
            Insert_student frame = new Insert_student();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit_btnActionPerformed

    private void gender_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_cbxActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "You sure you want to leave this page", "Submit", JOptionPane.YES_NO_OPTION);

        if(response == 0){
            setVisible(false);
        }
    }//GEN-LAST:event_backActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "You sure you want to exit", "Submit", JOptionPane.YES_NO_OPTION);

        if(response == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_exit1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        back.setOpaque(false);
        back.setContentAreaFilled(false);
        back.setBorderPainted(false);
        
        exit1.setOpaque(false);
        exit1.setContentAreaFilled(false);
        exit1.setBorderPainted(false);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> branch_cbx;
    private javax.swing.JButton clear_btn;
    private javax.swing.JComboBox<String> course_cbx;
    private javax.swing.JButton exit1;
    private javax.swing.JTextField father_txt;
    private javax.swing.JComboBox<String> gender_cbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField rollno_txt;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
