- Built a Student Result management system GUI application to help the admin store various data such as course result declaration , student details and to help student's check their own result.
- Added functionaly for admin to add/list student detail , add/list/update student result and for student to search for their result.
- Used mysql database to store/fetch data entered into the GUI.
- Made the application using java swing, awt and mysql database.
